# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(866, 648)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 400, 241, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textDisp = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textDisp.setObjectName("textDisp")
        self.verticalLayout.addWidget(self.textDisp)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(680, 310, 160, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ser_but = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.ser_but.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Consola Mono")
        self.ser_but.setFont(font)
        self.ser_but.setObjectName("ser_but")
        self.verticalLayout_2.addWidget(self.ser_but)
        self.cli_but = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Consola Mono")
        self.cli_but.setFont(font)
        self.cli_but.setObjectName("cli_but")
        self.verticalLayout_2.addWidget(self.cli_but)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(430, 50, 201, 251))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.sendText = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Consola Mono")
        self.sendText.setFont(font)
        self.sendText.setCheckable(False)
        self.sendText.setDefault(False)
        self.sendText.setFlat(False)
        self.sendText.setObjectName("sendText")
        self.verticalLayout_3.addWidget(self.sendText)
        self.setGraph = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Consola Mono")
        self.setGraph.setFont(font)
        self.setGraph.setCheckable(False)
        self.setGraph.setObjectName("setGraph")
        self.verticalLayout_3.addWidget(self.setGraph)
        self.sendGraph = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Consola Mono")
        self.sendGraph.setFont(font)
        self.sendGraph.setObjectName("sendGraph")
        self.verticalLayout_3.addWidget(self.sendGraph)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(69, 50, 241, 331))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.graphDisp = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.graphDisp.setText("")
        self.graphDisp.setAlignment(QtCore.Qt.AlignCenter)
        self.graphDisp.setObjectName("graphDisp")
        self.verticalLayout_4.addWidget(self.graphDisp)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(430, 500, 160, 80))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Quit = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Consola Mono")
        self.Quit.setFont(font)
        self.Quit.setObjectName("Quit")
        self.verticalLayout_5.addWidget(self.Quit)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(430, 310, 231, 150))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Add = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Add.sizePolicy().hasHeightForWidth())
        self.Add.setSizePolicy(sizePolicy)
        self.Add.setObjectName("Add")
        self.horizontalLayout.addWidget(self.Add)
        self.colon = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Consola Mono")
        self.colon.setFont(font)
        self.colon.setAlignment(QtCore.Qt.AlignCenter)
        self.colon.setObjectName("colon")
        self.horizontalLayout.addWidget(self.colon)
        self.Port = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Port.sizePolicy().hasHeightForWidth())
        self.Port.setSizePolicy(sizePolicy)
        self.Port.setMaximumSize(QtCore.QSize(45, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consola Mono")
        self.Port.setFont(font)
        self.Port.setText("")
        self.Port.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Port.setPlaceholderText("")
        self.Port.setObjectName("Port")
        self.horizontalLayout.addWidget(self.Port)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.restButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Consola Mono")
        self.restButton.setFont(font)
        self.restButton.setObjectName("restButton")
        self.verticalLayout_6.addWidget(self.restButton)
        self.conButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Consola Mono")
        self.conButton.setFont(font)
        self.conButton.setObjectName("conButton")
        self.verticalLayout_6.addWidget(self.conButton)
        self.disButton = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Consola Mono")
        self.disButton.setFont(font)
        self.disButton.setObjectName("disButton")
        self.verticalLayout_6.addWidget(self.disButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 866, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Quit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ser_but.setText(_translate("MainWindow", "Server"))
        self.cli_but.setText(_translate("MainWindow", "Client"))
        self.sendText.setText(_translate("MainWindow", "send text"))
        self.setGraph.setText(_translate("MainWindow", "set Graph"))
        self.sendGraph.setText(_translate("MainWindow", "send Graph"))
        self.Quit.setText(_translate("MainWindow", "Quit"))
        self.colon.setText(_translate("MainWindow", ":"))
        self.restButton.setText(_translate("MainWindow", "Reset"))
        self.conButton.setText(_translate("MainWindow", "Connect"))
        self.disButton.setText(_translate("MainWindow", "Disable Connection"))

